apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: azure-vote-front
  namespace: flux-system
spec:
  image: acrgitopsdemo.azurecr.io/voting-app
  interval: 1m0s
  secretRef:
  # name: regcred
    name: acr