apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: azure-vote-front
  # namespace: flux-system
  namespace: config-voting-app
spec:
  image: acrgitopsdemo.azurecr.io/voting-app
  interval: 1m0s
  secretRef:
  # name: regcred
    name: acr
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: azure-vote-front
  # namespace: flux-system
  namespace: config-voting-app
spec:
  imageRepositoryRef:
    name: azure-vote-front
  policy:
    semver:
      range: '>=1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  # namespace: flux-system
  namespace: config-voting-app
spec:
  interval: 1m30s
  sourceRef:
    kind: GitRepository
    name: config-voting-app
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: huihuan@microsoft.com
        name: huihuan
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  update:
    path: ./cluster-apps